# This is a basic workflow to help you get started with Actions

name: blog-friend-link-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: ["master", "v*", "release*"]
    tags: ["v*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: blog/friend-link

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: ./build.sh build

      - name: Publish
        if: github.event.pull_request.merged == true
        # if: github.ref_name == 'master'
        run: ./build.sh publish
        env:
          COMMIT_ID: ${{github.sha}}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
